### ISSUE TITLE
news apiで取得したデータの出力結果を報告

### ISSUE THREAD

**Issue by dev-satoshi** [dev-satoshi/safety-zone#13]

**Comment by SL9-1994** [comment]
https://newsapi.org/v2/top-headlines?country=jp&q=%E5%9C%B0%E9%9C%87&apiKey=[API_KEY]

{
"status": "ok",
"totalResults": 3,
"articles": [
{
"source": {
"id": null,
"name": "Yomiuri.co.jp"
},
"author": "読売新聞オンライン",
"title": "能登入りの岸田首相、被災者に「ご健康はどうですか」…中小企業再建や仮設整備は「早急に実行」 - 読売新聞オンライン",
"description": "岸田首相は１４日、能登半島地震の被災地視察のため、石川県輪島市と珠洲市を訪れた。県庁で記者団の取材に応じた首相は、２０２３年度予算の予備費から新たに１０００億円超の支出を月内に決定すると明らかにした。首相は中小企業の再",
"url": "https://www.yomiuri.co.jp/politics/20240114-OYT1T50134/",
"urlToImage": "https://www.yomiuri.co.jp/media/2024/01/20240114-OYT1I50106-1.jpg?type=ogp",
"publishedAt": "2024-01-14T09:48:00Z",
"content": ""
},
{
"source": {
"id": null,
"name": "Weathernews.jp"
},
"author": "ウェザーニュース",
"title": "明日15日(月)の天気予報 強い冬型気圧配置で荒天 日本海側は大雪や猛吹雪に警戒 - ウェザーニュース",
"description": "明日15日(月)は冬型の気圧配置となり、強い寒気が流れ込みます。日本海側を中心に雪が降り、特に北日本や東日本は大雪や猛吹雪に警戒が必要です。能登半島地震の被災地 北陸では災害の発生や拡大にも注意してください。",
"url": "https://weathernews.jp/s/topics/202401/140165/",
"urlToImage": "https://smtgvs.weathernews.jp/s/topics/img/202401/202401140165_top_img_A.png?1705217569",
"publishedAt": "2024-01-14T08:00:00Z",
"content": "{{topic.rank}}\r\n{{topic.pageTitle}}{{editTstr(topic.editTime)}}"
},
{
"source": {
"id": null,
"name": "Kobe-np.co.jp"
},
"author": null,
"title": "あの日と今 1995-2024 阪神・淡路大震災29年 - 神戸新聞NEXT",
"description": "アーケードの崩れた商店街は買い物客でにぎわい、焼け跡にはビルが幾つも建った。阪神・淡路大震災は１７日で発生から２９年。街に地震の爪痕が見えなくなっても語り継ぎたい。あの日のこと。そして、あの日からの歩みを。",
"url": "https://www.kobe-np.co.jp/news/society/202401/0017223678.shtml",
"urlToImage": "https://i.kobe-np.co.jp/news/society/202401/img/a_17223681.jpg",
"publishedAt": "2024-01-14T07:00:00Z",
"content": null
}
]
}

**Comment by dev-satoshi** [comment]
レビューOKです！
お疲れ様でした！
