### ISSUE TITLE
PWA化する方法を調べる

### ISSUE THREAD

**Issue by dev-satoshi** [dev-satoshi/safety-zone#23]

**Comment by SL9-1994** [comment]
### PWAに対応しているサイト => [Youtube, Qiita, Twitter]

## NextJSをPWA化する方法
- 1. [next-pwa](https://www.npmjs.com/package/next-pwa)のインストール
- 2. Publicフォルダ等にManifest.jsonを手動、又は[生成ツール](https://www.simicart.com/manifest-generator.html/)を使用して作成する。
- 3. Publicフォルダ等に4つの異なるサイズのicon画像を用意する。
- 4. next.config.jsにnext-pwaのモジュール設定を追記する。
- 5. 開発サーバーを起動すると、右上にアプリインストールボタンが表示される。

**Comment by dev-satoshi** [comment]
PWAは優先順位高いので、13を採用したい気持ちはあるのですが、一応Next13と14の違い・特徴をまとめたいです。
サブタスク：https://github.com/dev-satoshi/safety-zone/issues/27

**Comment by dev-satoshi** [comment]
お疲れ様です！
Next13を採用しましょう！
