### ISSUE TITLE
Next13と14の違い・特徴を調べる

### ISSUE THREAD

**Issue by dev-satoshi** [dev-satoshi/safety-zone#27]

**Comment by SL9-1994** [comment]
### Next13/14の違い
- TurboPackというRustで記述されたバンドラーの使用
- ローカルサーバー起動が53%高速化・Fast Refreshによるコード更新が94%高速化
- Next-Learnの追加
- サーバーアクションの安定版が実装
- 部分的プリレンダリングのプレビュー版が実装
- メタデータの改善

### 破壊的な変更
- 最小のNode.jsバージョンが18.17に変更
- @next/fontのサポートを廃止し、next/fontをサポート
- ImageResponseのimportをnext/serverからnext/ogに変更
- next exportコマンドが非推奨になり、output: 'export'をサポート
- next-swcのWASMターゲットが削除

## 結論
機能面での大きな変化はないと思われますが、開発をスムーズに進めやすくなったといえます。

**Comment by dev-satoshi** [comment]
お疲れ様です！
Next13を採用して、PWAを実装しましょう！
